[project]
name = "audio-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "tqdm>=4.67.1",
    "typer>=0.16.1",
    "yt-dlp>=2025.8.27",
]

[project.scripts]
audio-downloader = "audio_downloader.main:app"
